version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: "weekly"
  # deprecated for now as it requires a more in-depth overhaul
  open-pull-requests-limit: 0
